global:
  edition: ce
  hosts:
    https: true
    gitlab:
      name: gitlab.url
    registry:
      name: registry.url
    ssh: gitlab.url
  ###########
  # INGRESS #
  ###########
  ingress:
    enabled: true
    configureCertmanager: false
    class: nginx
    tls:
      secretName: wildcard-url
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"       

  ################
  # CERTIFICATES #
  ################
  #  certificates:
  #  customCAs:
  #    - secret: gitlab-gitaly-tls

  #######
  # KAS #
  #######
  # https://docs.gitlab.com/charts/charts/gitlab/kas/#disable-the-agent-server
  kas:
    enabled: false
 
  #########
  # REDIS #
  #########
  redis:
    auth:
      enabled: false
    host: 10.203.0.10

  #########
  # MINIO #
  #########
  # https://docs.gitlab.com/charts/charts/minio/#enable-the-sub-chart
  minio:
    enabled: false

  appConfig:
    object_store:
      enabled: true
      connection:
        secret: gitlab-rails-storage
        key: connection
    
    # https://docs.gitlab.com/16.6/charts/charts/globals.html#omniauth
    omniauth:
      enabled: true
      allowSingleSignOn:
        - openid_connect
      autoLinkUser:
        - openid_connect
      # autoSignInWithProvider: openid_connect
      syncProfileFromProvider: 
        - openid_connect
      blockAutoCreateUsers: true
      providers:
        - secret: gitlab-omniauth-provider-keycloak-openid

  ################
  ##  REGISTRY  ##
  ################
  ## https://docs.gitlab.com/charts/charts/registry/#enable-the-sub-chart
  registry:
    enabled: true
    
  ##############
  ##  GITALY  ##
  ##############
  # https://docs.gitlab.com/charts/charts/globals.html#external
  gitaly:
    enabled: false
    external:
      - name: default
        hostname: praefect.url
        port: 2305
        tlsEnabled: false
    authToken:
      secret: external-gitaly-token
      key: token
    tls:
      enabled: false
      # secretName: gitlab-gitaly-tls
 
  # https://docs.gitlab.com/charts/charts/globals#configure-postgresql-settings
  psql:
    password:
      secret: gitlab-postgresql-password
      key: postgresql-password
    host: url
    username: gitlab
    database: gitlab

gitlab-shell:
  enabled: true

nginx-ingress:
  enabled: false

gitlab:
  toolbox:
    enabled: true

  gitlab-shell:
  
    enabled: true
    sshDaemon: gitlab-sshd
    metrics:
      enabled: true
    authToken:
      secret: gitlab-gitlab-shell-secret
      key: secret

## https://docs.gitlab.com/charts/charts/registry/#configuration
registry:
  enabled: true
  maintenance:
    readonly:
      enabled: false
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false

  redis:
    cache:
      enabled: true
      host: 10.203.0.10
      db: 4
      password:
        enabled: false

  storage:
    secret: registry-storage  
    key: config

  database:
    enabled: true
    host: url
    name: registry
    user: gitlab
    password:
      secret: gitlab-postgresql-password
      key: postgresql-password
      
  gc:
    disabled: true
    maxbackoff: 24h
    noidlebackoff: false
    transactiontimeout: 10s
    reviewafter: 24h
    manifests:
      disabled: false
      interval: 5s
    blobs:
      disabled: false
      interval: 5s
      storagetimeout: 5s

# dependencies
postgresql:
  install: false

certmanager:
  install: false

prometheus:
  install: false

redis:
  install: false

gitlab-runner:
  install: false

