apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-test
spec:
  selector:
    matchLabels:
      app: whoami-test
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami-test
    spec:
      dnsPolicy: Default
      containers:
      - name: whoami-test
        image: {{ .Values.image.repository }} 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-test
spec:
  selector:
    app: whoami-test
  type: LoadBalancer
  loadBalancerIP: 10.0.4.150
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-test
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - # URL HOST
    secretName: # URL HOST
  rules:
  - host: # URL HOST
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-test
            port:
              number: 80

